services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      # MySQL Config
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_DATABASE=sport_booking
      # Redis Config (Matches the service name below)
      - REDIS_HOST=redis-cache  # 
      - REDIS_PORT=6379

    depends_on:
      redis-cache:
        condition: service_started
      mysql:
        condition: service_healthy

# ---- mysql Service ---
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=sport_booking
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

# ---- Redis Service ---
  redis-cache:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mysql_data:
